uncovering_2015_schedule = [
  ["Wed, Sept 9, 2015", "Introduction to the Fathers"],
  ["Wed, Sept 16, 2015", "The Didache"],
  ["Wed, Sept 23, 2015", "No class"],
  ["Thurs, Oct 1, 2015", "First Clement (move to Thurs b/c Tyburn event conflict)"],
  ["Wed, Oct 7, 2015", "Ignatius’ epistles [Eph and Rom]"],
  ["Wed, Oct 14, 2015", "Ignatius’ epistles [Philad, Smyr, Polyc]"],
  ["Wed, Oct 21, 2015", "The Martyrdom of Polycarp"],
  ["Thurs, Oct 29, 2015", "Justin’s First Apology (move to Thurs b/c Tyburn event conflict)"],
  ["Wed, Nov 4, 2015", "Justin’s Dialogue with Trypho"],
  ["Wed, Nov 11, 2015", "Martyrdom of Justin and The Martyrs of Vienne and Lyon"],
  ["Wed, Nov 18, 2015", "No class"],
  ["Wed, Nov 25, 2015", "No class"],
  ["Wed, Dec 2, 2015", "Irenaeus’ Adversus Haereses"],
  ["Wed, Dec 9, 2015", "Tertullian’s Short Way with Heretics"],
  ["Wed, Dec 16, 2015", "Tertullian’s On Penitence"],
  ["Wed, Dec 23, 2015", "No class"],
  ["Wed, Dec 30, 2015", "No class"],
  ["Wed, Jan 6, 2016", "Eusebius on the Theodoti - HE 5.28; Tertullian’s Against Praxeas"],
  ["Wed, Jan 13, 2016", "Monarchianism and Trinitarianism overview"],
  ["Wed, Jan 20, 2016", "Review of what we have learned so far"]
];
